#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define PACKET_SIZE 15
#define KEYWORD_SIZE 4
#define EMG_VALUE_SIZE 4
#define HANDLE_SIZE 1
#define EMG_HANDLE 'e'
#define END_HANDLE 'f'
#define BATTERY_HANDLE 'b'
#define BATTERY_STATUS_SIZE 2
#define MOTOR_HANDLE 'm'
#define MOTOR_STATUS_SIZE 2
#define VOLTAGE_COEFFICIENT 1
#define PACKET_KEYWORD "armb"
#define DEVICE_ID_START 4
#define DEVICE_ID_SIZE 4


#endif // DEFINITIONS_H
