set(__QT_DEPLOY_TARGET_qcustomplot_FILE C:/Users/Admin/Documents/ArmBionicsGUI/Win32/build/output/amd64/Release/bin/libqcustomplot.dll)
set(__QT_DEPLOY_TARGET_qcustomplot_TYPE SHARED_LIBRARY)
set(__QT_DEPLOY_TARGET_qcustomplot_RUNTIME_DLLS C:/Qt/6.7.2/mingw_64/bin/Qt6PrintSupport.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_ArmBionicsGUIWin_FILE C:/Users/Admin/Documents/ArmBionicsGUI/Win32/ArmBionicsGUIWin.exe)
set(__QT_DEPLOY_TARGET_ArmBionicsGUIWin_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_ArmBionicsGUIWin_RUNTIME_DLLS C:/Qt/6.7.2/mingw_64/bin/Qt6SerialPort.dll;C:/Users/Admin/Documents/ArmBionicsGUI/Win32/build/output/amd64/Release/bin/libqcustomplot.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6PrintSupport.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Widgets.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Gui.dll;C:/Qt/6.7.2/mingw_64/bin/Qt6Core.dll)
